//-----------------------------------------------------------------------------
// top.v — Top-level module for AUP-ZU3 LED Demo
//
// This module is pure wiring — it instantiates all submodules and connects
// them together. It does not contain any logic of its own.
//
// Clock: The AUP-ZU3 provides a 100 MHz differential LVDS clock on pins D7/D6.
//        An IBUFDS primitive converts this to a single-ended clock signal.
//
// Reset: A power-on reset is generated by counting clock cycles after startup.
//        After 2^20 cycles (~10.5 ms at 100 MHz), the reset is released.
//        This gives the FPGA time to stabilize after configuration.
//
// Data flow:
//   Buttons → debounce → rainbow_ctrl → hsv_to_rgb → rgb_pwm → RGB LED pins
//   Switches → LED pins (direct assign)
//
// Teaching points:
//   - Structural Verilog: connecting modules by instantiation and wiring
//   - IBUFDS: differential-to-single-ended clock buffer (Xilinx primitive)
//   - Power-on reset generation without an external reset button
//   - generate loops for repetitive instantiation
//-----------------------------------------------------------------------------

module top (
    // Clock (100 MHz differential LVDS)
    input  wire       clk_p,
    input  wire       clk_n,

    // 8 Switches
    input  wire [7:0] sw,

    // 4 Pushbuttons
    input  wire [3:0] btn,

    // 8 White LEDs
    output wire [7:0] led,

    // 4 RGB LEDs (active high, one pin per channel)
    output wire       rgb0_r, rgb0_g, rgb0_b,
    output wire       rgb1_r, rgb1_g, rgb1_b,
    output wire       rgb2_r, rgb2_g, rgb2_b,
    output wire       rgb3_r, rgb3_g, rgb3_b
);

    // ========================================================================
    // Clock: differential → single-ended
    // ========================================================================
    wire clk;

    IBUFDS clk_ibuf (
        .I  (clk_p),
        .IB (clk_n),
        .O  (clk)
    );

    // ========================================================================
    // Power-on reset generator
    // ========================================================================
    // Count 2^20 clock cycles (~10.5 ms at 100 MHz), then release reset.
    reg [19:0] reset_cnt = 20'd0;
    reg        rst_n     = 1'b0;

    always @(posedge clk) begin
        if (!rst_n) begin
            if (reset_cnt == 20'hFFFFF)
                rst_n <= 1'b1;
            else
                reset_cnt <= reset_cnt + 20'd1;
        end
    end

    // ========================================================================
    // Switch → LED direct mapping
    // ========================================================================
    assign led = sw;

    // ========================================================================
    // Button debouncers (4 instances)
    // ========================================================================
    wire [3:0] btn_rise;  // single-cycle pulses for each button

    genvar b;
    generate
        for (b = 0; b < 4; b = b + 1) begin : btn_debounce
            debounce #(
                .CLK_FREQ    (100_000_000),
                .DEBOUNCE_MS (10)
            ) u_debounce (
                .clk     (clk),
                .rst_n   (rst_n),
                .btn_in  (btn[b]),
                .btn_out (),           // stable output not needed
                .btn_rise(btn_rise[b])
            );
        end
    endgenerate

    // ========================================================================
    // Rainbow controller → 4 hue values
    // ========================================================================
    wire [31:0] hue_bus;  // 4 x 8-bit hue values, packed

    rainbow_ctrl #(
        .NUM_LEDS (4)
    ) u_rainbow (
        .clk          (clk),
        .rst_n        (rst_n),
        .speed_up     (btn_rise[0]),
        .speed_down   (btn_rise[1]),
        .reverse      (btn_rise[2]),
        .phase_change (btn_rise[3]),
        .hue_out      (hue_bus)
    );

    // ========================================================================
    // HSV-to-RGB converters (4 instances, combinational)
    // ========================================================================
    wire [7:0] r [0:3];
    wire [7:0] g [0:3];
    wire [7:0] b_ch [0:3];  // 'b' is reserved in some tools, use b_ch

    genvar c;
    generate
        for (c = 0; c < 4; c = c + 1) begin : hsv_conv
            hsv_to_rgb u_hsv (
                .hue   (hue_bus[8*c +: 8]),
                .red   (r[c]),
                .green (g[c]),
                .blue  (b_ch[c])
            );
        end
    endgenerate

    // ========================================================================
    // RGB PWM generators (4 instances)
    // ========================================================================
    wire [3:0] pwm_r, pwm_g, pwm_b;

    generate
        for (c = 0; c < 4; c = c + 1) begin : pwm_gen
            rgb_pwm u_pwm (
                .clk        (clk),
                .red_duty   (r[c]),
                .green_duty (g[c]),
                .blue_duty  (b_ch[c]),
                .red_out    (pwm_r[c]),
                .green_out  (pwm_g[c]),
                .blue_out   (pwm_b[c])
            );
        end
    endgenerate

    // ========================================================================
    // Map PWM outputs to RGB LED pins
    // ========================================================================
    assign rgb0_r = pwm_r[0];  assign rgb0_g = pwm_g[0];  assign rgb0_b = pwm_b[0];
    assign rgb1_r = pwm_r[1];  assign rgb1_g = pwm_g[1];  assign rgb1_b = pwm_b[1];
    assign rgb2_r = pwm_r[2];  assign rgb2_g = pwm_g[2];  assign rgb2_b = pwm_b[2];
    assign rgb3_r = pwm_r[3];  assign rgb3_g = pwm_g[3];  assign rgb3_b = pwm_b[3];

endmodule
